### ISSUE TITLE
event-stream.merge

### ISSUE THREAD

**Issue by robrich** [gulpjs/acceptance#3]
Using `event-stream` indicates gulp 2.0 recomendations, and hints at an obsolete plugin.  However `event-stream` has `merge` which still seems the best way to combine two streams into one.  How should we reconcile this in automated acceptance tests?

**Comment by yocontra** [comment]
There is no reason to use event-stream, just look at it's package.json to find what the merge really is

**Comment by robrich** [comment]
Sadly, merge doesn't come from elsewhere, though it appears it could easily
be broken out. See
https://github.com/dominictarr/event-stream/blob/master/index.js#L32-59

**Comment by sindresorhus** [comment]
https://github.com/Raynos/lazy-concat-stream
https://www.npmjs.org/package/merge-stream
https://github.com/mariocasciaro/multistream-merge

**Comment by yocontra** [comment]
That ^

Streams have a shitload of tools available as modules, if you need anything from event-stream and it doesn't have a module just npm search

**Comment by robrich** [comment]
Awesome! Thanks.
