### ISSUE TITLE
event-stream

### ISSUE THREAD

**Issue by stevemao** [gulpjs/acceptance#4]
It says `event-stream` is "Old streams + bloated kitchen sink" in the README. But `event-stream` appears at many places in the [main gulp repo](https://github.com/gulpjs/gulp/search?utf8=%E2%9C%93&q=event-stream) and the [org](https://github.com/search?p=1&q=org%3Agulpjs+event-stream&type=Code), even in [useful-resources](https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/README.md#useful-resources). This may confuse many devs.

**Comment by yocontra** [comment]
@stevemao PRs to remove it would be appreciated

**Comment by stevemao** [comment]
@contra do you mean remove the rule here or replace it with other streams in other repos?

I personally don't like event-stream same reason stated here.

**Comment by yocontra** [comment]
@stevemao Removing it from other repos

**Comment by phated** [comment]
`event-stream` won't work with gulp 4 because they don't actually return real streams in some cases and `end-of-stream` requires it to be a real stream with all the events.

I think that plugin authors shouldn't use kitchen sink modules when they are building their modules but I think kitchen sinks (like the `mississippi` module) should be suggested for end users.  @contra thoughts?

**Comment by stevemao** [comment]
> I think that plugin authors shouldn't use kitchen sink modules when they are building their modules but I think kitchen sinks (like the mississippi module) should be suggested for end users.

-1 unless @maxogden has a good argument.

**Comment by phated** [comment]
@stevemao why -1 on people writing gulpfiles using it?

**Comment by stevemao** [comment]
Sorry it was probably a rough opinion. In a gulpfile I don't wanna construct a stream unless it's a `merge`. Looking at the streams provided by `mississippi` none of them would be useful in gulpfiles. I don't encourage end-users to write a tiny plugin in their gulpfile.

In general when I use streams I wanna be very specific about what I'm using.

**Comment by phated** [comment]
@stevemao I actually think the `pipe` method (provided by the pump module) is extremely important for clean gulpfiles, `each` is better than gulp-map or whatever it is called.  Not every method will be useful to everyone but I've seen many gulpfiles that would use multiple of them.

**Comment by phated** [comment]
Just noticed this and laughed because event-stream.

**Comment by stevemao** [comment]
I forgot I opened this... But using ES modules seems a good fit for importing some of the `mississippi` streams
